[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
mint_nft = "D7PPVzQqSZmhYnsWRsLgiZ5qgmy2ZiDgEvqWWu91oJs7"

[programs.devnet]
mint_nft = "D7PPVzQqSZmhYnsWRsLgiZ5qgmy2ZiDgEvqWWu91oJs7"

[programs.localnet]
mint_nft = "D7PPVzQqSZmhYnsWRsLgiZ5qgmy2ZiDgEvqWWu91oJs7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"  
program = "tests/metaplex_token_metadata_program.so"
